server:
  port: 8001

spring:
  application:
    name: GINC

  # H2 Setting Info
  h2:
    console:
      enabled: true
      path: /h2-console
  # Database Setting Info
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: