server:
  port: 8001

spring:
  application:
    name: GINC

  profiles:
    active: dev
    include: secret

  # H2 Setting Info
  h2:
    console:
      enabled: true
      path: /h2-console
  # Database Setting Info
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

  batch:
    job:
      enabled: false

jwt:
  secret-key: ${jwt.secret-key}
