server:
  port: 8001

spring:
  application:
    name: GINC

  profiles:
    active: dev
    include: secret

  # H2 Setting Info
  h2:
    console:
      enabled: true
      path: /h2-console
  # Database Setting Info
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
# 배치코드 변경으로 사용 x
#  batch:
#    job:
#      enabled: false

jwt:
  secret-key: ${jwt.secret-key}